### ISSUE TITLE
Page is disappearing in react app made with Vite

### ISSUE THREAD

**Issue by Sahani18** [gilbarbara/react-joyride#912] opened 2023-06-05 06:12 UTC
```
Hi,

When I was using this package in react app with environment of "create-react-app" then it is working fine. But Now I have to implement joyride in a react app made with "Vite" the page is disappearing. When I'm addding this line " define: { global: "window" } " in the vite.config.ts file then it is working fine. But when I'm pushing the code to production it is throwing issue of " define: { global: "window" } " this property.

Need help
Thanks & Regards

```

**Comment by gilbarbara** [comment] 2023-06-06 00:40
Duplicate of #772

**Closed by gilbarbara** 2023-06-06 00:40 UTC
