### ISSUE TITLE
Re-invoking the tour after completing it, does not show overlay.

### ISSUE THREAD

**Issue by akmtagline** [gilbarbara/react-joyride#1004] opened 2024-02-16 07:18 UTC
## 🐛 Bug Report

I have a tour set up for multiple pages on my website. We also have a button to take a tour again by clicking it. I went through all of the steps and completed the tour. It works as expected with the overlay and the tooltip. Now, if I click the button to retake the tour, I can only see the tooltip and not the overlay.

I have a custom close icon on each step. I'm closing the tour by calling the `skip` function from the helpers.
`helpers.skip()`

I am re-invoking the tour by calling the `reset` function with true as its first argument.
`helpers.reset(true)`

## To Reproduce

1. Start a tour.
2. Complete the tour by going through all of the steps or Skip the tour after 2 or 3 steps.
3. Try to invoke the tour again.
4. You will see the tooltip without overlay.

## Expected behavior

It should show a tour with overlay same as the first tour.

**Comment by Nigui** [comment] 2024-02-16 10:01
Same behavior here. 
Easy to reproduce on joyride-demo project : disable beacon on first step, skip the tour then click restart button.

**Comment by Sairamtagline** [comment] 2024-02-16 10:07
@Nigui 
I also observed strange behavior with this issue in my project. I don't know how it works. But, if the overlay is not visible and your first step target is a body with the center placement, you can click on the restart button twice to activate the overlay.

**Comment by akmtagline** [comment] 2024-02-16 10:08
@Nigui
I also observed strange behavior with this issue in my project. I don't know how it works. But, if the overlay is not visible and your first step target is a body with the center placement, you can click on the restart button twice to activate the overlay.

**Comment by Nigui** [comment] 2024-02-17 22:21
Hello @gilbarbara 
I think that I've found a solution for this issue. 

[`if (changedFrom('lifecycle', LIFECYCLE.INIT, LIFECYCLE.READY))`](https://github.com/gilbarbara/react-joyride/blob/6c84d3e8ff10d5f4acc21bee6ee1f544f9b94c0a/src/components/Step.tsx#L115)

Should contains `LIFECYCLE.TOOLTIP` in "from" state, like:

`if (changedFrom('lifecycle', [LIFECYCLE.INIT,LIFECYCLE.TOOLTIP], LIFECYCLE.READY))`

The reason of the bug is that [`setPopper`](https://github.com/gilbarbara/react-joyride/blob/6c84d3e8ff10d5f4acc21bee6ee1f544f9b94c0a/src/components/Step.tsx#L195-L200) is executed after being in `TOOLTIP` lifecycle state. So it gets back to `READY` state. Unfortunately, Overlay is not rendered when lifecycle state is not `TOOLTIP`. 

I don't know if it's the best solution, but it seems to do the job. 

Do you know how long it would take to integrate the fix? Thank you for this lib btw ;)

**Comment by akmtagline** [comment] 2024-02-19 05:00
@Nigui @gilbarbara 

I have found a workaround for this issue. This can help you identify and fix the issue. 

Before, I was calling only the `skip` method to close the tour.
`const closeTour = () => helper.skip()`

But, now if I also call the `cleanupPoppers` method, the tour works as expected on restart. You can access this method using ref.
`const closeTour = () => {
       helper.skip();
       joyrideRef.current?.store?.cleanupPoppers();
  }
`

**Note:** I have also used my custom footer button for "Done" and called the above function on the click of it.

**Comment by Nigui** [comment] 2024-02-22 10:13
@gilbarbara I've tested your fix in my project and it works perfectly. Thank you! Can't wait for the release 😀

**Comment by gilbarbara** [comment] 2024-02-22 18:50
Released as 2.7.3
Thanks

**Closed by gilbarbara** 2024-02-22 18:50 UTC
