### ISSUE TITLE
Spotlight not transparent on Edge (opacity not working)

### ISSUE THREAD

**Issue by yaskor** [gilbarbara/react-joyride#402] opened 2018-07-17 07:43 UTC
>Expected behavior
![expected](https://user-images.githubusercontent.com/518934/42803279-d2e22412-89a5-11e8-92cc-f90dc940458a.png)

>Actual behavior
![actual](https://user-images.githubusercontent.com/518934/42803291-d74ac004-89a5-11e8-9cd5-6daff2ad26c3.png)

>React version
16.4.1

>React-Joyride version
2.0.0-13

>Browser name and version
Microsoft Edge

**Comment by yaskor** [comment] 2018-07-17 20:01
I've found a solution.

no background-color for: joyride-overlay
instead add a box- shadow to: joyride-spotlight

0px 0px 0px 9999px rgba(0,0,0,0.5)

If you let me, i will fix it

**Comment by MilllerTime** [comment] 2018-07-24 05:56
As of 2.0.0-11, this worked in Edge. I believe joyride gracefully fell back to using the "legacy" box-shadow technique on it's own. After upgrading to 2.0.0-13, I too am experiencing this issue. It appears a regression happened between pre-release 11 and 13.

Interestingly, I'm seeing a grey spotlight on Edge, not just a dimmed version as shown above. For me, joyride is clearly trying to use the hard-light blend mode trick on Edge, which fails and renders as grey.

Edge:
![edge](https://user-images.githubusercontent.com/7662720/43119443-6c036bb8-8ee4-11e8-9ffb-e808a7a7a94b.png)

Chrome:
![chrome](https://user-images.githubusercontent.com/7662720/43119444-6f1a1504-8ee4-11e8-8b76-d25858a302c9.png)

**Comment by MilllerTime** [comment] 2018-07-24 06:13
I believe the change to [this line](https://github.com/gilbarbara/react-joyride/commit/9e46226de66e9156953017b94fd0cca5b7c2cf04#diff-a40ec4c4d5e8754526ade5899ead309bR79) a few days ago is the source of the problem. 

The change marks Edge as no longer being a legacy browser, but Edge [still doesn't support mix-blend-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode#Browser_compatibility). Therefore, Edge should still be considered "legacy".

**Comment by MilllerTime** [comment] 2018-08-03 06:00
Just following up on this since it's been over a week. Any plans to release a fix for this? Reverting the change I linked to above should do it. Is there anything blocking a release?

**Comment by gilbarbara** [comment] 2018-08-06 01:57
@MilllerTime yes, time. :)
Fixed in 2.0.0-14

**Closed by gilbarbara** 2018-08-06 01:57 UTC
Labels: V2, bug

**Comment by MilllerTime** [comment] 2018-08-06 04:06
Totally understand. Thank you for the update, and your time :)
