### ISSUE TITLE
Placement Prop in Steps not working

### ISSUE THREAD

**Issue by lightninglu10** [gilbarbara/react-joyride#466] opened 2019-01-08 18:50 UTC
## 🐛 Bug Report

Trying to set placement of an item in the steps: 

```
steps = [
            {
              target: '#card',
              title: 'CARD',
              content: 'Track the Card Activity.',
              disableBeacon: true,
              placement: 'bottom',
            },
...
```

## Expected behavior

Bottom placement, but instead get top placement

**Comment by gilbarbara** [comment] 2019-01-08 19:06
Is there space available at the bottom to render the tooltip? 
Please post an example

**Comment by lightninglu10** [comment] 2019-01-08 19:08
Yes there is space: 

<img width="338" alt="screen shot 2019-01-08 at 11 06 57 am" src="https://user-images.githubusercontent.com/2453737/50852851-937abe00-1335-11e9-80e9-716adb07c5ec.png">


I console logged the prop going into this:

```
<Floater
          component={(
            <Tooltip
              continuous={continuous}
              controlled={controlled}
              helpers={helpers}
              index={index}
              setTooltipRef={this.setTooltipRef}
              size={size}
              isLastStep={index + 1 === size}
              step={step}
            />
          )}
          debug={debug}
          getPopper={this.setPopper}
          id={`react-joyride:${index}`}
          isPositioned={step.isFixed || isFixed(target)}
          open={this.open}
          placement={step.placement}
          target={step.target}
          {...step.floaterProps}
        >
```

and step.placement IS 'bottom', but in the HTML, x-placement on floater is top:

<img width="525" alt="screen shot 2019-01-08 at 11 08 16 am" src="https://user-images.githubusercontent.com/2453737/50852915-bc02b800-1335-11e9-85a1-ff7a26c05235.png">

**Comment by lightninglu10** [comment] 2019-01-08 19:10
Seems like I misunderstood the bottom prop -- there is not enough space for it to render BELOW the component, but is there a way for it to be pointing downwards from the center instead of up? I guess the center prop works.

**Comment by gilbarbara** [comment] 2019-01-08 19:30
Yeah, since your target fills most of the screen there's not much popper.js can do. Maybe change the target the "assigned to" block?
Anyway, this is not a bug.
Good luck!

**Closed by gilbarbara** 2019-01-08 19:30 UTC
