### ISSUE TITLE
Cannot read property 'ease' of undefined

### ISSUE THREAD

**Issue by mahburg** [gilbarbara/react-joyride#327] opened 2018-03-25 02:25 UTC
Joyride works as normal until I click next on first step. Then the entire root div of React goes blank.

Console displays these errors:

> The above error occurred in the <Joyride> component:
    in Joyride (at User.js:189)
    in div (at User.js:188)
    in User (created by Connect(User))
    in Connect(User) (created by Route)
    in Route (at AppFrame.js:13)
    in Switch (at AppFrame.js:11)
    in AppFrame (at App.js:12)
    in Router (created by HashRouter)
    in HashRouter (at App.js:11)
    in App (at index.js:11)
    in Provider (at index.js:10)

> index.js:18 Uncaught TypeError: Cannot read property 'ease' of undefined
    at Object.scroll [as top] (index.js:18)
    at Joyride.componentDidUpdate (index.js:494)
    at commitLifeCycles (react-dom.development.js:8778)
    at commitAllLifeCycles (react-dom.development.js:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at commitRoot (react-dom.development.js:10050)
    at performWorkOnRoot (react-dom.development.js:11017)
    at performWork (react-dom.development.js:10967)
    at batchedUpdates (react-dom.development.js:11086)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)

**Comment by gilbarbara** [comment] 2018-03-25 22:20
Duplicate of #320

**Closed by gilbarbara** 2018-03-25 22:20 UTC
