### ISSUE TITLE
Deprecated Reference to popper.js@1.16.1

### ISSUE THREAD

**Issue by buchananwill** [gilbarbara/react-joyride#1025] opened 2024-05-02 18:25 UTC
## 🐛 Bug Report

The 2.8.1 version of react-joyride still references 0.7.9 of react-floater, which in turn references 1.16.1 of popper.js.

## To Reproduce

Visible in the package.json files for the respective packages.:

## Expected behavior

For react-joyride to reference the most recent version of react-floater, which no longer references the deprecated dependency.

## Link to repl or repo 

https://github.com/gilbarbara/react-floater/blob/v0.7.9/package.json.

versus:

https://github.com/gilbarbara/react-floater/blob/v0.9.3/package.json

## Suggested:

  "dependencies": {
    "@gilbarbara/deep-equal": "^0.3.1",
    "deep-diff": "^1.0.2",
    "deepmerge": "^4.3.1",
    "is-lite": "^1.2.1",
    "react-floater": "^0.9.3",
.....

In:

https://github.com/gilbarbara/react-joyride/blob/main/package.json

**Comment by gilbarbara** [comment] 2024-05-03 07:30
Yes, it's known. However this is library isn't still compatible with react-floater above 0.7.x

**Comment by gilbarbara** [comment] 2024-05-03 07:31
Duplicate of #937

**Closed by gilbarbara** 2024-05-03 07:31 UTC

**Comment by buchananwill** [comment] 2024-05-11 19:48
Thanks for replying. I had a look at some of the incompatibilities and resolved some of them on a forked version. I got stuck though with the test behaviour for the Controlled.tsx tour. If you have a moment to answer a query or two, I'd be happy to put some more time in to work through the rest of the tests/migration?

**Comment by gilbarbara** [comment] 2024-05-12 05:00
Hey @buchananwill 
Sure, ask away.

**Comment by buchananwill** [comment] 2024-05-12 15:37
Thanks! It's a great library and having looked at several of the alternatives, far, far easier to understand and get running within my own project. I had another crack at the test suite today, and I can now make it pass all the tests, however:

- I had to change several of the values for how many times the callback was called. I'm inferring this is related to the different rendering/lifecycle patterns of 0.7.9 with class components, versus the functional components of 0.9.3 in react-floater. _Do you have any flowchart/record that explains the significance of any of these numbers?_
- In the Standard test, the 'should render the STEP 6 Tooltip' test was failing due to expecting "UPDATE" as the action, and receiving "NEXT". I tried a couple of things to change how this state was propagating across different stages, but this caused 'should render the STEP 2 Tooltip' to fail, because it was now receiving the wrong state. I couldn't see any reason why these two tests should be expecting different outcomes, so changed the tests to match. _Was there a reason for this difference/discrepancy between the two tests? I thought it might be todo with rendering a tooltip without a target element, but couldn't see a simple way to distinguish that case. _
- I also had to comment out the test expecting that Tooltip 4 would render in the DOM, since the 0.9.3 react-floater doesn't pass through the ID and render the Tooltip invisibly, like the 0.7.9 version did. _Is this ok? Or would you rather include an updated test for this specific case?_

My updated fork is here:

https://github.com/buchananwill/react-joyride/tree/buchananwill-patch-1

I've left in a lot of my comments that I used to predict/figure out what effect my changes were going to have, but I can go through and delete them all if you are happy with my changes and want to pull these updates onto the main branch, but keep the code cleaner.
