### ISSUE TITLE
Highlight spotlight sometimes is displayed in  improper position (scroll related)

### ISSUE THREAD

**Issue by keul** [gilbarbara/react-joyride#376] opened 2018-05-24 15:07 UTC
>Expected behavior

The highlight overlay should be placed normally

>Actual behavior

In some cases if I use `scrollToFirstStep` the highlight overlay (*please note*: _not_ the overlay of the first step! Weird...) is placed at the wrong position.

See image below:

![joyride-issue](https://user-images.githubusercontent.com/284924/40492772-8b675890-5f71-11e8-8ae1-ea24a08f3b67.png)

The highlight overlay should be placed on the plus icon (note that the Floater is at the right position). All is working perfectly when i put `scrollToFirstStep={false}`.

>Steps to reproduce the problem

That's the sad part... I tried to reproduce with same React and Joyride versions at https://codesandbox.io/s/q7oopyqwkq with no luck. I'm not able to find what is going on there.

If you have any suggestion helping debug this issue let me know, I understand maybe I'm able to provide enough information, so feel free to close the issue if it's not enough for an idea from your side.

>React version

15.6.2

>React-Joyride version

2.0.0-11

**Comment by keul** [comment] 2018-05-25 16:17
I modified the issue title because I found that `scrollToFirstStep` is not the realm issue here. This is related to *page scrolling* (so this is why probably `scrollToFirstStep` trigger the issue in my env): if I manually scroll the page, on some steps spotlight is badly positioned too. I _think_ that the issue is on calculating the some values in `stylesSpotlight`.

Keep looking into this...

**Comment by keul** [comment] 2018-05-25 16:57
OK, I think I found the origin of the issue so I was able to reproduce it on a codesandbox...

https://q7oopyqwkq.codesandbox.io/

To reproduce the issue you should resize the browser and use scrolling, for easily explain it here two animation.

Here we don't have the issue (I didn't scrolled anywhere):

![no-bug](https://user-images.githubusercontent.com/284924/40556238-3f4254e8-604c-11e8-9939-b19377b36c23.gif)

Here the same application but I scrolled a little the page, so you can see the bug:

![bug](https://user-images.githubusercontent.com/284924/40556271-6026b14a-604c-11e8-8872-6105bfbe9f0f.gif)

## Reason

Seems that problem came from scrollparent.js dependency (so maybe is a bug in this library?).
There's an explicit management of `overflow` css prop: https://github.com/olahol/scrollparent.js/blob/dd25def14fa307cd4dc0c71460808232cb797100/scrollparent.js#L23

As soon as one of parent element use overflow we fall into this problem.

I don't fully understand why scrollparent.js is doing this. Any idea?

**Comment by nicubarbaros** [comment] 2018-07-03 09:18
anyone got a fix for this?

**Comment by keul** [comment] 2018-07-05 08:07
@nicubarbaros no, I just tried to remove overflow usage form my CSS where I was able to do so.

**Comment by nicubarbaros** [comment] 2018-07-11 07:39
@keul Damn it. I just removed the spotlight for now. Great plugin but has this issue which is quite harmful.

**Comment by gilbarbara** [comment] 2018-07-15 21:40
Can you please try `react-joyride@2.0.0-12` and let me know if the problem is there?
Please post an example in codesandbox.

**Comment by keul** [comment] 2018-07-16 07:06
@gilbarbara tested the same codesandbox above (still https://codesandbox.io/s/q7oopyqwkq) after updating to 2.0.0-12 and I've the same issue (the gif I attached is still valid to reproduce the error).

**Comment by keul** [comment] 2018-09-17 14:40
A quick-and-dirty test for posterity.

As I said above the issue seems to came from scrollparent.js but I get no answer from them.

If I manually modify the scrollparent.js source file inside my node_modules, removing the scroll check, **the error is fixed in my environment**.

See commented lines below.

```javascript

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory);
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.Scrollparent = factory();
  }
}(this, function () {
  var regex = /(auto|scroll)/;

  var parents = function (node, ps) {
    if (node.parentNode === null) { return ps; }

    return parents(node.parentNode, ps.concat([node]));
  };

  var style = function (node, prop) {
    return getComputedStyle(node, null).getPropertyValue(prop);
  };

  var overflow = function (node) {
    return style(node, "overflow") + style(node, "overflow-y") + style(node, "overflow-x");
  };

  var scroll = function (node) {
   return regex.test(overflow(node));
  };

  var scrollParent = function (node) {
    if (!(node instanceof HTMLElement || node instanceof SVGElement)) {
      return ;
    }

    var ps = parents(node.parentNode, []);

    // for (var i = 0; i < ps.length; i += 1) {
    //   if (scroll(ps[i])) {
    //     return ps[i];
    //   }
    // }

    return document.scrollingElement || document.documentElement;
  };

  return scrollParent;
}));
```

I'm 100% sure that this code is there for a reason, I guess for handling `overflow: scroll` or `auto` usecases. So I'm sure that this fix can't work in every case, but seems good enough for me.

**Comment by j0o009k** [comment] 2018-10-12 15:35
This fix does cause other issues with some components, in my experience. For one component it is throwing the floater off in a big way. Very frustrating.

**Comment by keul** [comment] 2018-10-13 14:36
@j0o009k as I said above: my fix worked in **my** environment. I guess you have components where the use of `overflow` matters.

**Comment by simonwaw** [comment] 2018-10-23 23:35
@keul - I also have the same issues in my app - this hack to scrollParent also resolves the issue for me.  @gilbarbara any chance we can remove the need for this dependancy in a future version?

**Comment by sturdynut** [comment] 2018-11-09 20:30
**Super hack**...not proud, but if you are in need of an immediate fix:

Basically, get spotlight element, then reset the top to the target offset top.  I subtracted 10 so it fits correctly.  I put this in the callback for the tour and only applied it to the steps that had the scroll issue.  Note that there is a delay in the spotlight element being added to the dom so you may need to add a `window.setTimeout(..., 100)` around this to get it to run after the spotlight element has been added.

Code example:
```
const targetEl = $(target);
if (targetEl) {
  window.setTimeout(() => {
    const spotlight = document.querySelector('.joyride-spotlight');
    if (spotlight) {
      spotlight.style.top = (targetEl.offset().top - 10) + 'px';
    }
  }, 100);
}
```

Disclaimer:  I have not thoroughly tested this, just a quick hack that got me by for now until the issue is fixed.

**Comment by catamphetamine** [comment] 2018-12-28 11:07
We've just tried upgrading to v2 and we immediately stumbled upon the issu.
If the user doesn't scroll at all while the "tour" is being shown then it's not buggy (it still doesn't automatically scroll the next step into view but that's some another issue).
If the user scrolls during the "tour" though then the "spotlight" is positioned incorrectly.
It's not a blocker though and we'll just roll back to v1 which works fine-enough.

**Comment by gilbarbara** [comment] 2018-12-28 16:30
@catamphetamine Can you please try again with `2.0.0-rc` and let me know?

**Comment by catamphetamine** [comment] 2018-12-28 17:36
@gilbarbara 
Same issue.
The tooltip is positioned correctly, but the "spotlight" is not.
It looks as if you were subtracting `window.scrollY` from `spotlight.top`: if `window.scrollY` is `0` then the "spotlight" is positioned correctly, but when `window.scrollY` is `N` then `spotlight.top` is `N` pixels less than it should have been.

**Comment by keul** [comment] 2018-12-28 20:19
@gilbarbara is something changed in the lib packaging? I tried the same old codesandbox with latest `2.0.0-rc` but now I get an error:

```
ModuleNotFoundError
Could not find module in path: 'react-joyride/es/constants' relative to '/src/index.js'
```

...while doing...

```import { ACTIONS, EVENTS } from "react-joyride/es/constants";```

**Comment by gilbarbara** [comment] 2018-12-29 05:35
@keul I'll try to fix it today! :)

**Comment by gilbarbara** [comment] 2018-12-29 12:17
@keul Can you please try this [sandbox](https://codesandbox.io/s/4x86y3lpx4) and see if the problem continues?

**Comment by keul** [comment] 2018-12-29 19:20
Ehi @gilbarbara it's working there! 🎉 

I don't fully understand what is doing the trick from my codesandbox to your ones! Can you enlight me?

**Comment by gilbarbara** [comment] 2018-12-29 20:08
@keul The `.node` class had an `overflow-y` property, which messes up with the scrolling detection.
I'm testing a new scroll parent detection to avoid this problem.

**Comment by gilbarbara** [comment] 2018-12-31 04:54
`2.0.0-rc.1` adds a dirty fix for unused scroll parents with overflow that should handle most cases.
If you still are having problems, let me know

**Closed by gilbarbara** 2018-12-31 04:54 UTC
Labels: V2, bug, help wanted

**Comment by harunurhan** [comment] 2020-03-06 11:20
This still happens to me with the very basic use case, when step target out of viewport (down), so it scrolls down, tooltip is correctly placed, but the spotlight is somewhere up in the page.

@gilbarbara

**Comment by gilbarbara** [comment] 2020-03-06 11:28
Hey @harunurhan 

Please provide a https://codesandbox.io/ demo or similar.

**Comment by harunurhan** [comment] 2020-03-06 12:59
@gilbarbara I think my issue is similar to https://github.com/gilbarbara/react-joyride/issues/548, and as it was said in that issue, it is tricky to provide a sandbox reproduction.

**Comment by gilbarbara** [comment] 2020-03-07 13:26
@harunurhan Ok, but that's impossible for me to help without seeing what's going on with the code...

**Comment by ekfuhrmann** [comment] 2023-09-08 20:18
For those who come across this issue and are looking for a solution, I was having a similar problem with the spotlight being offset when the user had scrolled slightly down the page. It ended up being that in my case I had `height: 100%` on my `html` element and that was throwing off the auto scroller and by extension the spotlight positioning. Removing `height: 100%` in my case resolved the issue and might be worth trying for those who run into a similar problem.
