### ISSUE TITLE
Allow pointer-events on a tooltip in a hole.

### ISSUE THREAD

**Issue by choyongjoon** [gilbarbara/react-joyride#184] opened 2017-01-11 02:30 UTC
If a hole is big, part of tooltip can be in the hole. Then the pointer-events is disabled on that part.

For example, user can not click the button.

![2017-01-11 11 27 39](https://cloud.githubusercontent.com/assets/1563230/21832813/15dfa6a8-d7f1-11e6-99c5-40d7a2c96e42.png)

**Comment by IanVS** [comment] 2017-01-11 02:31
This looks like a duplicate of https://github.com/gilbarbara/react-joyride/issues/182.  Can you please try with version 1.8.2?

**Comment by choyongjoon** [comment] 2017-01-11 02:36
Oh, that was fast. Thanks. When will be version 1.8.2 published to npm?

**Comment by IanVS** [comment] 2017-01-11 02:40
Ah, I thought it had been published already.  @gilbarbara needs to do that, so it won't be until tomorrow.

**Closed by IanVS** 2017-01-11 02:40 UTC

**Comment by IanVS** [comment] 2017-01-11 18:09
FYI 1.8.2 is now published to npm.
