### ISSUE TITLE
Scrolling to the top of the page when target is inside an element with relative position

### ISSUE THREAD

**Issue by Alpa84** [gilbarbara/react-joyride#590] opened 2020-07-22 19:20 UTC
## 🐛 Bug Report
react-joyride scrolls to the top of the page when the target is inside an element with relative position

## To Reproduce

1. Open the CodeSandox link below
https://codesandbox.io/s/react-joyridescrollissue-2v5uv
2. Scroll to the bottom of the page
3. Click the beacon

## Expected behavior

It should scroll to the bottom of the page, where the target is.

## Link to repl or repo (highly encouraged)
https://codesandbox.io/s/react-joyridescrollissue-k263u

I have a PR ready to fix this issue
https://github.com/gilbarbara/react-joyride/compare/master...Alpa84:scroll_to_fix

**Comment by gilbarbara** [comment] 2020-07-29 03:13
Hey @Alpa84 

I've encountered this problem over and over again and most of the time is a weird css setup.
In your sandbox example, it can be fixed by removing the unused position and top attributes...

[s]

**Comment by Alpa84** [comment] 2020-07-29 16:08
@gilbarbara  thanks for checking out the sandbox example.
This issue seems to appear when the target is inside an element with a position:relative attribute.
For example if you are using bootstrap and your target is inside a bootstrap card.

https://codesandbox.io/s/react-joyride-scroll-issue-bootstrap-vd8q7?file=/src/index.js

That example reproduces the issue just using bootstrap with no additional css changes
The problem seems to be here

https://github.com/gilbarbara/react-joyride/compare/master...Alpa84:scroll_to_fix#diff-fad7a32697c71bf983590f8c617075ebL267

The offsetTop property only returns 

> the number of pixels from the top of the closest relatively positioned parent element.
From:  https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop

The solution I implemented in my fork is inspired in this article:
https://medium.com/@alexcambose/js-offsettop-property-is-not-great-and-here-is-why-b79842ef7582

**Comment by Alpa84** [comment] 2020-07-29 16:09
Here is my proposed fix:
https://github.com/gilbarbara/react-joyride/compare/master...Alpa84:scroll_to_fix

**Comment by nilsDE** [comment] 2020-08-05 09:20
Thanks @Alpa84 , I just encountered the same issue and as you stated above it was due to bootstraps use of position:relative. I didn't find a solution so I hope your PR will be approved.

**Comment by aelfric** [comment] 2020-08-18 20:51
We were running into this same problem.  Unfortunately, even switching to the PR didn't fix it. In our case, I inherited a page with several levels of nested elements with `position: fixed` and `position: relative`.  Here is our workaround for now with the existing library release.  There's probably a better way to do it.

We are using the controlled version of the Joyride component, but I suspect this will work with the uncontrolled as well.  We disabled automatic scrolling in the Joyride props and added a callback property.  Inside the callback, I have:

```javascript
function scrollIntoView(element){
    element.scrollIntoView({
      behavior: "smooth",
      block: "center"
    });
}

function handleJoyrideCallback(data) {
    const {action, index, type, status, step, lifecycle} = data;
    if(lifecycle === LIFECYCLE.INIT) {
      waitForElement(step.target).then(scrollIntoView);
    }

     // Other code not relevant to scrolling...
}
````

We are using controlled components because some navigation needs to take place in between steps.  `waitForElement` is taken here https://paul.kinlan.me/waiting-for-an-element-to-be-created/ but if you aren't dealing with elements that may not be there when you want to scroll to them, you could replace this with:

```javascript
document.querySelector(step.target).scrollIntoView({
      behavior: "smooth",
      block: "center"
    });

```

**Comment by Alpa84** [comment] 2020-08-18 21:52
Hi @aelfric  ! 
Thanks for trying out my PR. I'm sorry it didn't work out in your case.
It would be great to have a sandbox example to repro the error

**Comment by gilbarbara** [comment] 2020-12-10 21:50
Fixed in f1abf475372c0e6b78fd8c04098a4b5ef543d29e

**Closed by gilbarbara** 2020-12-10 21:50 UTC

**Comment by SamyakJain2020** [comment] 2022-03-10 12:06
Hi i am also facing the same issue , what should I do ??

**Comment by Ricordy** [comment] 2023-12-05 18:45
Same issue here guys

**Comment by gilbarbara** [comment] 2023-12-05 19:38
I need a reproducible minimal example in codesandbox or stackblitz

**Comment by Ricordy** [comment] 2023-12-06 11:59
The same exact version that started the issue, but with current version of react and react-joyride

[Link for sandbox](https://codesandbox.io/p/sandbox/react-joyride-scroll-issue-forked-fhpx9p?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clph36hcu00073b6hwf563bl7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clph36hcu00033b6h5475nzsm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clph36hcu00043b6hguij8qvl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clph36hcu00063b6hnsnmt8jl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clph36hcu00033b6h5475nzsm%2522%253A%257B%2522id%2522%253A%2522clph36hcu00033b6h5475nzsm%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clph36hcu00063b6hnsnmt8jl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clph36hcu00053b6hcvveut30%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clph36hcu00063b6hnsnmt8jl%2522%252C%2522activeTabId%2522%253A%2522clph36hcu00053b6hcvveut30%2522%257D%252C%2522clph36hcu00043b6hguij8qvl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clph36hcu00043b6hguij8qvl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by gilbarbara** [comment] 2023-12-07 04:38
@Ricordy 
Since there's no space below the target, the scroll gets lost. Setting the placement to "top" fixed it

**Comment by Ricordy** [comment] 2023-12-10 21:45
Hey, it wasn't enough. I just sent this small template to be easier to undertsand, but in my production website, it's happening to components all over the page, but just components with relative position. I will send a print and the script of the component: 

`<section
      id="puzzle"
      className={cn(
        "mx-auto flex w-full max-w-[1338px] flex-col px-6 md:px-0",
        className
      )}
    >
      {isConnected && (
        <h2 className="pb-12 text-2xl font-medium uppercase md:ml-[58px]">
          My Puzzle
        </h2>
      )}

      {isConnected && (
        <div className="relative flex max-w-[1408px] items-center overflow-hidden md:ml-[-70px]">
          <div
            className={`swiper-prev-22 absolute left-0 z-20 flex h-full items-start justify-center pl-3 pt-6 md:pl-16 md:pt-[190px]`}
          >
            {currentLevel !== 1 && (
              <Image
                src={
                  isAboveMd || levels?.at(currentLevel - 1)?.locked
                    ? "/icons/pagination-previous-black.svg"
                    : "/icons/pagination-previous.svg"
                }
                width={38}
                height={38}
                alt="Previous"
              />
            )}
          </div>

          <section
            className={cn(" relative z-10 flex w-full flex-col items-center ")}
          >
            <div className="swiper-wrapper relative z-10 flex ">
              <Swiper
                modules={[Navigation, A11y]}
                className="swiper w-full"
                spaceBetween={80}
                slidesPerView={isAboveMd ? 1.2 : "auto"}
                navigation={{
                  nextEl: `.swiper-next-22`,
                  prevEl: `.swiper-prev-22`,
                }}
                updateOnWindowResize
                observer
                observeParents
                // initialSlide={0}
                // loop
                centeredSlides
                onSlideChange={(swiperCore) => {
                  const { activeIndex } = swiperCore;
                  setCurrentLevel(activeIndex + 1);
                }}
              >
                {dbLevels?.map((level, idx) => (
                  <SwiperSlide
                    key={level.title}
                    className={cn(
                      "flex items-center justify-center  ",
                      currentLevel - 1 !== idx ? "blur-md" : ""
                    )}
                  >
                    <Level
                      level={idx + 1}
                      userLevel={userLevel?.toNumber() as number}
                      bg={level.bg.url}
                      description={level.description}
                      profitRange={level.profitRange}
                      nextProfitRange={
                        dbLevels?.at(idx + 1)?.profitRange as string
                      }
                      userPieces={userPieces as BigNumber[]}
                      claimLevel={actionClaimLevel}
                    />
                    <div className="mt-16 flex flex-col">
                      <div className=" grid max-w-6xl grid-cols-1 gap-6 pb-36 md:grid-cols-4">
                        {userLevel?.gt(currentLevel) ? (
                          <div className="h-90 firstPieceOverallStep relative col-span-2 flex flex-col items-center justify-between rounded-md bg-neutral-100">
                            <div
                              className="absolute left-0 top-0 h-full w-full  rounded-md border-2 border-white"
                              style={{
                                boxShadow:
                                  "4px 7px 30px 0px rgba(195, 162, 121, 1)",
                              }}
                            ></div>
                            <div className="absolute left-0 top-0 h-full w-full rounded-lg border-4 border-white bg-zinc-300">
                              <Image
                                alt="NFT"
                                src={dbLevels.at(idx)?.nft?.url as string}
                                fill
                                className="rounded-[5px]"
                                style={{ objectFit: "cover" }}
                              />
                            </div>
                          </div>
                        ) : (
                          (userPieces && userPieces.length < 10 && (
                            // </div>
                            <div className="h-90 mainCard firstPieceOverallStep relative flex flex-col items-center justify-between gap-6 rounded-md bg-neutral-100">
                              <h2 className="pt-6 text-center text-[24px] font-semibold uppercase leading-normal tracking-wider text-black">
                                Your
                                <br />
                                next NFT
                              </h2>
                              <div className="pieceProgree1stStep flex flex-col items-center justify-center gap-3">
                                <span className="  text-center text-[14px] font-normal leading-none tracking-wide text-neutral-600">
                                  Progress
                                </span>
                                <span className="text-center text-[40px] font-light leading-10 tracking-widest text-black">
                                  <NumericFormat
                                    value={claimPieceProgress?.toString()}
                                    displayType="text"
                                    fixedDecimalScale
                                    decimalSeparator=","
                                    thousandSeparator="."
                                    decimalScale={0}
                                    suffix=" %"
                                  />
                                </span>
                                <span className="text-center text-[14px] font-normal leading-none tracking-wide text-neutral-600">
                                  You&apos;re almost there!
                                </span>
                                <span className="text-[16px] font-normal leading-normal text-neutral-600">
                                  <span className="text-[16px] font-semibold leading-normal text-black">
                                    <NumericFormat
                                      value={
                                        claimPieceProgressValue &&
                                        noDecimals(
                                          claimPieceProgressValue.toNumber()
                                        )
                                      }
                                      displayType="text"
                                      fixedDecimalScale
                                      decimalSeparator=","
                                      thousandSeparator="."
                                      decimalScale={0}
                                      prefix="$ "
                                    />
                                  </span>{" "}
                                  |{" "}
                                  <NumericFormat
                                    value={(5000 * currentLevel).toString()}
                                    displayType="text"
                                    fixedDecimalScale
                                    decimalSeparator=","
                                    thousandSeparator="."
                                    decimalScale={0}
                                    prefix="$ "
                                  />
                                </span>
                              </div>
                              <MyAlertButton
                                triggerButtonLabel={
                                  isLoadingClaimPiece
                                    ? "Loading..."
                                    : `Claim Piece`
                                }
                                confirmAction={actionClaimPiece}
                                triggerButtonClassname="whitespace-nowrap border-emerald-700 px-12 text-emerald-700 hover:bg-emerald-700 hover:text-white claimPieceButtonStep"
                                variant="outline"
                                isTriggerDisabled={!userAllowedToClaimPiece}
                                alertDescription="Are you sure you want to claim this puzzle piece? This action cannot be undone."
                                confirmLabel="Claim Piece"
                                alertTitle="Claim Puzzle Piece?"
                              />

                              <div className="bottom-0 left-0 flex h-3 w-full self-end rounded-b-md bg-progressBackground">
                                <div
                                  className={cn(
                                    "rounded-bl-md bg-progressHighlight",
                                    Math.abs(claimPieceProgress?.toNumber()) >=
                                      100
                                      ? "rounded-br-md"
                                      : ""
                                  )}
                                  style={{
                                    width: `${
                                      Math.abs(
                                        claimPieceProgress?.toNumber()
                                      ) >= 100
                                        ? 100
                                        : Math.abs(
                                            claimPieceProgress?.toNumber()
                                          )
                                    }%`,
                                  }}
                                ></div>
                              </div>
                            </div>
                          )) ||
                          (userPieces && userPieces.length == 10 && (
                            <div className="h-90 firstPieceOverallStep relative flex flex-col items-center justify-between rounded-md bg-neutral-100 align-middle">
                              <div className="mt-[132px] flex flex-col justify-center align-middle ">
                                <h2 className="pt-6 text-center text-[24px] font-semibold uppercase leading-normal tracking-wider text-[#C3A279]">
                                  You got all
                                  <br />
                                  Pieces
                                </h2>
                                <span className=" text-center text-[14px] font-normal  text-neutral-600">
                                  Your final NFT is ready
                                </span>
                              </div>

                              <div className="bottom-0 left-0 flex h-3 w-full self-end rounded-b-md bg-progressBackground">
                                <div
                                  className={cn(
                                    "rounded-bl-md bg-[#C3A279]",
                                    Math.abs(
                                      claimPieceProgress?.toNumber() || 0
                                    ) >= 100
                                      ? "rounded-br-md"
                                      : ""
                                  )}
                                  style={{
                                    width: `${
                                      Math.abs(
                                        claimPieceProgress?.toNumber() || 0
                                      ) >= 100
                                        ? 100
                                        : Math.abs(
                                            claimPieceProgress?.toNumber() || 0
                                          )
                                    }%`,
                                  }}
                                ></div>
                              </div>
                            </div>
                          ))
                        )}
                        {!userPieces && (
                          <div className="h-90 relative flex flex-col items-center justify-center rounded-md bg-neutral-100 align-middle">
                            <div className="flex flex-col justify-center align-middle ">
                              Loading...
                            </div>
                          </div>
                        )}

                        {puzzlePieces
                          ?.slice((currentLevel - 1) * 10, currentLevel * 10)
                          .map((puzzle, idx) => (
                            <div
                              key={puzzle.tokenid}
                              className={cn(
                                "relative rounded-md border-2 border-[#8C9592/20]",
                                `secondPieceNftWillApperStep-${idx}`
                              )}
                            >
                              <CarouselItem
                                title={puzzle.title}
                                amount={
                                  userPuzzlePieces
                                    ?.at(idx)
                                    ?.toNumber() as number
                                }
                                isConnected={isConnected}
                                image={
                                  userLevel?.gt(currentLevel) ||
                                  ((userPuzzlePieces &&
                                    userPuzzlePieces.at(idx)?.toNumber()) ||
                                    0) > 0
                                    ? puzzle?.imageCollected?.url
                                    : puzzle.image.url
                                }
                              />
                            </div>
                          ))}
                        {currentLevel < 4 && !userLevel?.gt(currentLevel) && (
                          <div className="h-90 relative flex flex-col items-center justify-center rounded-md border-2 border-[#C3A279] align-middle">
                            {(userPieces && userPieces.length < 10 && (
                              <div className="flex flex-col items-center justify-center align-middle ">
                                <Image
                                  src="/nfts/next_level.svg"
                                  alt="Symbol"
                                  width={165}
                                  height={165}
                                  className="mb-2"
                                />
                                <div className="m-2 flex flex-col items-center justify-center text-primaryGold">
                                  <h3>
                                    {idx < 2
                                      ? `NFT Level ${idx + 2}`
                                      : `Final NFT`}
                                  </h3>
                                  <p className="text-center">
                                    You can claim it when you
                                  </p>
                                  <p>get 10 different pieces</p>
                                </div>
                              </div>
                            )) || (
                              <div className="flex flex-col items-center justify-center align-middle ">
                                <Image
                                  src="/nfts/car_completed.svg"
                                  alt="Symbol"
                                  width={165}
                                  height={165}
                                  className="mb-2"
                                />
                                <div className="m-2 flex flex-col items-center justify-center text-primaryGold">
                                  <h3>
                                    {" "}
                                    {idx < 2
                                      ? `NFT Level ${idx + 2}`
                                      : `Final NFT`}
                                  </h3>
                                  <Button
                                    variant={"outline"}
                                    onClick={actionClaimLevel}
                                    disabled={
                                      (userPieces && userPieces.length < 10) ||
                                      (userLevel?.toNumber() as number) >
                                        idx + 2
                                    }
                                    className={cn(
                                      "mt-[32px] border-primaryGold bg-primaryGold font-sans text-[14px] font-medium text-white hover:bg-primaryGold",
                                      (userLevel?.toNumber() as number) >
                                        idx + 2
                                        ? "bg-primaryGold text-white"
                                        : ""
                                    )}
                                  >
                                    {idx < 2
                                      ? `Claim Level ${idx + 2}`
                                      : "CLAIM FINAL LEVEL"}
                                  </Button>
                                </div>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </SwiperSlide>
                ))}
              </Swiper>
            </div>
          </section>

          <div
            className={cn(
              "swiper-next-22 absolute right-0 z-20 flex h-full items-start pr-3 pt-6 md:pr-16 md:pt-[190px]",
              currentLevel > 2 ? "hidden" : ""
            )}
          >
            <Image
              src={
                isAboveMd || levels?.at(currentLevel - 1)?.locked
                  ? "/icons/pagination-next-black.svg"
                  : "/icons/pagination-next.svg"
              }
              // className="fill-black text-black"
              width={38}
              height={38}
              alt="Next"
            />
          </div>
        </div>
      )}
    </section>
   `
   
   In this case, for example, the "firstPieceOverallStep" will slide to the wrong place, but it is nowhere near the end of the page: 
   
   
<img width="1419" alt="Captura de ecrã 2023-12-10, às 21 44 44" src="https://github.com/gilbarbara/react-joyride/assets/42589197/eac60c06-9fee-45d6-8f05-9e38347ba42c">


In this case, what could be a possible solution? Do you need more info to see?

**Comment by gilbarbara** [comment] 2023-12-11 21:48
Hey @Ricordy 
Sorry, I can't debug pasted code. Please update the sandbox with some examples

**Comment by Ricordy** [comment] 2023-12-14 18:36
Hey, i was able to reproduce the error in a smaller scale, when you go to the 2nd step, it will slid you all the way up. (for some reason it is not showing the highlight boxes, but this isn't and issue in my side, just the scrolling)

[Sandbox](https://codesandbox.io/p/sandbox/ecstatic-shirley-2l2stm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq2bej1500063b6gkngafiju%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq2bej1500023b6gh3y4l1gf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq2bej1500033b6gn4a99ugz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq2bej1500053b6gql5k2m00%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B49.5912188703589%252C50.4087811296411%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq2bej1500023b6gh3y4l1gf%2522%253A%257B%2522id%2522%253A%2522clq2bej1500023b6gh3y4l1gf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3ylgw900023b6gza73weqg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A32%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A32%252C%2522endColumn%2522%253A79%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq3ylgw900023b6gza73weqg%2522%257D%252C%2522clq2bej1500053b6gql5k2m00%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq2bej1500043b6gxm0ilwkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq2bej1500053b6gql5k2m00%2522%252C%2522activeTabId%2522%253A%2522clq2bej1500043b6gxm0ilwkz%2522%257D%252C%2522clq2bej1500033b6gn4a99ugz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq2bej1500033b6gn4a99ugz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Ricordy** [comment] 2023-12-18 16:01
Hey @gilbarbara. Did you had the time to see the example. I have been trying to find a solution but it seams that I am not reaching anywhere. Thank you for your assistance!

**Comment by gilbarbara** [comment] 2023-12-20 22:46
Hey @Ricordy 
Can you try this version and report back?
`npm i react-joyride@next`

**Comment by Ricordy** [comment] 2023-12-21 11:14
It's working perfectly! 

Thank you @gilbarbara 🙏

**Comment by andresmarty** [comment] 2024-02-27 15:46
@gilbarbara im having the same issue (parent is using position:relative)....tried 2.7.4 version but still not working

**Comment by gilbarbara** [comment] 2024-02-27 20:20
Hey @andresmarty 

Please post a codesandbox link with a minimal reproducible example.

**Comment by Ralk** [comment] 2024-02-29 15:26
@Ricordy @andresmarty  Try adding `disableScrolling` in your step directly. We had same issue and that worked for us.

Hope this helps!

**Comment by Ricordy** [comment] 2024-03-05 09:29
For me it is working now. @andresmarty. If you are using next use the version for next if not I might not have a solution for you. 

Good luck!
