### ISSUE TITLE
Arrow is misplace in IE

### ISSUE THREAD

**Issue by catncradle** [gilbarbara/react-joyride#517] opened 2019-05-23 20:00 UTC
## 🐛 Bug Report

When running the tour in IE, every tooltip with the placement of "left" misplace the arrow

## To Reproduce

Steps to reproduce the behaviour:
run a tour in IE and have a few steps that have a "left" placement

## Expected behaviour
![image](https://user-images.githubusercontent.com/35584695/58282130-de402400-7d72-11e9-95b7-b45afa50cbb4.png)

## In IE 
![image](https://user-images.githubusercontent.com/35584695/58282163-ee580380-7d72-11e9-8b0d-03c7d0bb3cef.png)

I apologize for the photos, but I had to take them on my phone as my work computer doesn't allow me to post photos on github, and I don't have IE on my macbook so I had to take them on my phone.

I fixed this locally by updating the built files for react-floater
```
else if (placement.startsWith('left')) {
      arrow.right = 0;
      arrow.top = 0;
      arrow.bottom = 0;
      arrow.position = 'static';
    }
```
the corresponding file is in the react-floater repo @ src/components/Floater/Arrow.js
this didn't break the functionality in other browsers for me.
I wasn't sure if this was a react floater bug so I opened the issue here.

really appreciate your work, and thanks in advance

**Comment by LightOri** [comment] 2019-10-03 13:40
Any updates on that issue?
It still reproduces with official [tour example](https://react-joyride.com/) on IE11.
![image](https://user-images.githubusercontent.com/24460915/66131634-750fcd80-e5fc-11e9-9945-8b2ec3c4db71.png)

**Comment by gilbarbara** [comment] 2019-10-03 14:03
PRs welcome

**Comment by jucallej** [comment] 2019-11-22 10:29
Hey! I'll look into this and make the PRs 😀. 

I think first some upstream projects need to be updated, as I think `react-floater` is responsible for the arrow, but it's something in either `scrollparent` or  `scroll-doc` the reason why the highlight area is not correct (one returns the whole html element, while the other returns the body and they both should return the same). I'll look into those as well!

**Comment by jucallej** [comment] 2019-12-04 09:48
Just as a recap:

* In `react-floater` this PR was merged https://github.com/gilbarbara/react-floater/pull/64
* We need to release `react-floater` to npm.
* We need to review https://github.com/gilbarbara/react-joyride/pull/560 and merge it.
* We need to update the dependency of `react-floater` in `react-joyride`.
* We need to release `react-joyride` to npm.

@gilbarbara when you have some time could you check if it makes sense? I'm happy to help in whatever I can 😀

**Comment by jucallej** [comment] 2019-12-12 17:05
Hey @gilbarbara! Did you have time to check this? Let me know if I can help with something 😀

**Comment by gilbarbara** [comment] 2019-12-12 20:07
I'll look into it when have some time...

**Closed** 2019-12-14 22:25 UTC
Labels: help wanted, legacy

**Comment by caiosamarone** [comment] 2020-11-23 21:19
@jucallej Hey! the bug of scrolling I.E its fixed? Im getting the same error of @LightOri.  I've put disableScrolling={true} and worked, but if the user scroll the page after a step, the bug comes.

**Comment by jucallej** [comment] 2020-11-24 17:01
Hey @caiosamarone ! Have you installed https://github.com/mathiasbynens/document.scrollingElement? It's on the readme https://github.com/gilbarbara/react-joyride `If you need to support legacy browsers you need to include the scrollingelement polyfill` 😀 Also if I remember correctly I did some custom logic on top of react-joyride to not allow users to scroll when the tour was on (it was part of my requirements). Maybe the same would work for you?
