### ISSUE TITLE
Skip button doesn't show when new steps are added (worked in v1.3.6)

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#91] opened 2016-07-07 23:05 UTC
Today I upgraded Joyride from v1.3.6 to the latest. After updating my deprecated `stepCallback` function everything is working great again, except for the skip button. I have it enabled, and it shows for the first step, but doesn't show for the steps after that.

If I restart the tour it seems to fix things, so I think something regressed in regards to that action. Since my steps after step 1 are called in child components, it seems only the steps listed at the time the start is called get the `showSkipButton` option set correctly.

Something I need to change between versions, or a regression?

Thanks!

**Comment by gilbarbara** [comment] 2016-07-08 04:37
Hey,
I couldn't reproduce this behavior.
I've included a new step in the demo that is added 3 seconds after the tour has started and the previous steps kept showing the skip button.

However I removed the skip link in the last step since the tour would be completed after closing it anyway.
How many step do you have?

**Comment by stinoga** [comment] 2016-07-08 15:29
@gilbarbara AHA! That's the problem. I have some steps in my tour that aren't in the dom when the tour starts. I show them as the tour progresses. (They are usually user actions but I show them via Redux actions for the tour). When they are shone, their attached tour steps are added to the steps and the tour is restarted.

Because of this, the tour sees the previous step before the Redux action as the last step, and hides the skip button.

Is there a way around this?

**Comment by gilbarbara** [comment] 2016-07-10 00:10
I reverted that functionality.
Try 1.4.6 👍

**Closed by gilbarbara** 2016-07-10 00:10 UTC
