### ISSUE TITLE
Updated to latest version - getting TypeErrors when starting the Joyride

### ISSUE THREAD

**Issue by matt-koevort** [gilbarbara/react-joyride#477] opened 2019-01-24 10:48 UTC
## 🐛 Bug Report

After upgrading to the latest version of react-joyride, whenever I toggle a joyride to run, there are two TypeErrors that cause my page to crash.

## To Reproduce

Setting the run prop to true. The error seems to be in the `tooltipComponent` prop, as soon as I add it, I see the following error:
TypeError
Invalid parameter: element must be an HTMLElement

This error occurs even when providing a simple function that returns a `div` element.

## Expected behavior

The joyride should start and open as it once did. The page currently crashes.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/ypl2y2wmz9

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
npx: installed 1 in 1.972s

  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 515.29 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.5.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/workspace/catalogue-admin-frontend/node_modules/.bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
```

**Comment by gilbarbara** [comment] 2019-01-24 10:59
This is a duplicate of #470

**Closed by gilbarbara** 2019-01-24 10:59 UTC
