### ISSUE TITLE
Turning beacon off

### ISSUE THREAD

**Issue by karolselak** [gilbarbara/react-joyride#171] opened 2017-01-05 20:53 UTC
Beacon in this repo is quite interesting feature, but I believe that's always better to have a choice than not to have. Making beacon optional seems quite simple to realise, but I think it can prevent lots of potential problems and irritation.

And ability of customizing beacon also seems to be a good idea ;)

Thanks for all you have done ;)

**Comment by quentin-** [comment] 2017-01-07 00:26
Hello,

I don't maintain this repo but I think beacons are already optional if you have autoStart and "continuous" type.

**Comment by IanVS** [comment] 2017-01-14 16:00
@karolselak thanks for the suggestion.  I like the idea of making it easier to provide a custom beacon component.  

As for turning off the beacon, what would you use instead?  How would you trigger the tooltip to open?

**Comment by karolselak** [comment] 2017-01-14 18:00
In my app I have own icon responsible for going back to the ride at any time (and I inform user about it in first step). Now it works together with beacon and maybe that's not bad, but in my case that'll be sufficient when on "x" button all ride will be closing with saving the last step. Clicking on my icon you'll be able to resume that. And I think that maybe some additional option of restarting all ride will be userful in this case.

**Comment by trpham** [comment] 2017-04-03 23:19
How to turn off all beacons? I have a button to trigger the tour, so I don't really need it to show anywhere!

**Comment by bertrand-riviere** [comment] 2017-06-27 10:07
I'm in the same case (don't want the beacon at all as I use autoStart + my own button).
Here is the quick workaround I've found:

```
callback(data) {
  if (data.action === 'close' && data.type === 'step:after') {
    this.setState({ shouldRun: false });
  }
}
```
...

```
<Joyride
  autoStart
  run={this.state.shouldRun}
  callback={this.callback}
  ...
/>
```

**Comment by AndrewStobie** [comment] 2017-07-17 15:12
@bertrand-riviere did that work. I am using the same set state and formula you are using but I am still getting beacons appearing when I close it and don't want it to be running.

**Comment by bertrand-riviere** [comment] 2017-07-18 08:41
@AndrewStobie sure it does work for me (using v1.10.1).. Here is the complete code:

```
import React, { Component } from 'react';
import Joyride from 'react-joyride';

import 'react-joyride/lib/react-joyride-compiled.css';

export default class ProductTour extends Component {
  constructor(props) {
    super(props);
    this.state = {
      shouldRun: true,
    };
    this.callback = this.callback.bind(this);
  }

  callback(data) {
    if (data.action === 'close' && data.type === 'step:after') {
      // This explicitly stops the tour (otherwise it displays a "beacon" to resume the tour)
      this.setState({ shouldRun: false });
    }
  }

  render() {
    const tourSteps = [
      {
        position: 'bottom',
        selector: '.ant-layout-header',
        text: 'Text for header',
        title: 'Title for header',
      },
      {
        position: 'top',
        selector: '.ant-layout-footer',
        text: 'Text for footer',
        title: 'Title for footer',
      },
    ];

    return (
      <Joyride
        steps={tourSteps}
        autoStart
        run={this.state.shouldRun}
        debug={false}
        type="continuous"
        disableOverlay
        showStepsProgress
        callback={this.callback}
        holePadding={0}
      />
    );
  }
}
```

**Comment by AndrewStobie** [comment] 2017-07-18 13:47
I'm using that logic and for some reason the set state is not happening before beacon:before and the beacon rendering in the callbacks as well.

**Comment by jduncanRadBlue** [comment] 2017-10-04 17:05
I have an icon in the application, that when clicked sets the state for the isRunning to true.  The problem is, when I do that, the beacon appears rather than the first popup.  I'd like to eliminate the beacon all together and just start the tour.  Here is my code:

`export class Application extends Component {
    constructor(props) {
        super(props);       
        this.callback = this.callback.bind(this);
        this.state = {
            config: {},
            hovered: '',
            steps: [],
            isRunning: false,
        }
    }

    componentWillReceiveProps(nextProps) {
        // if the user is logged in and the screen is large the drawer should be open
         if(nextProps.userData != this.props.userData) {
             if(nextProps.userData != null && window.innerWidth >= 1200) {
                 this.props.openDrawer();
             }
         }
    }

    componentDidMount() {
        const steps = [
            {
                title: 'First Step',
                text: 'Start using the <strong>joyride</strong>',
                selector: '.qa-Application-header',
                position: 'inherit',

            },
            {
                title: 'Creating a DataPack',
                text: 'This will take you to the Create Datapack Page. <br/> Blah blah blah!',
                selector: '.qa-DataPackLinkButton-RaisedButton',
                position: 'bottom',
            }

        ]
        this.joyrideAddSteps(steps);
    }
      
    joyrideAddSteps(steps) {
        let newSteps = steps;

        if (!Array.isArray(newSteps)) {
            newSteps = [newSteps];
        }

        if (!newSteps.length) return;

        this.setState(currentState => {
            currentState.steps = currentState.steps.concat(newSteps);
            return currentState;
        });
    }

    callback(data) {
        if (data.action === 'close' && data.type === 'step:after') {
            // This explicitly stops the tour (otherwise it displays a "beacon" to resume the tour)
            this.setState({ isRunning: false });
        }
    }

    handleJoyride() {
        this.setState({isRunning: true})
    }

    render() {
        const {steps, isRunning} = this.state;

        const img = <img style={styles.img} src={logo}/>

        const childrenWithContext = React.Children.map(this.props.children, (child) => {
            return React.cloneElement(child, {
                context: {config: this.state.config}
            });
        });

        return (
            <MuiThemeProvider muiTheme={muiTheme}>
                <div style={{backgroundColor: '#000'}}>
                    <Joyride
                        callback={this.callback}
                        ref={'joyride'}
                        debug={false}
                        steps={steps}
                        autostart
                        type={'continuous'}
                        disableOverlay
                        showSkipButton={true}
                        showStepsProgress={true}
                        locale={{
                            back: (<span>Back</span>),
                            close: (<span>Close</span>),
                            last: (<span>Done</span>),
                            next: (<span>Next</span>),
                            skip: (<span>Skip</span>),
                        }}
                        run={isRunning}/>
                    <Banner />

                    <header className="qa-Application-header" style={{height: '95px'}}>
                        <AppBar
                            iconElementRight={<Info style={{color: 'white'}}/>}
                            onRightIconButtonTouchTap={this.handleJoyride.bind(this)}
                            className={'qa-Application-AppBar'}
                            style={styles.appBar}
                            title={img} onLeftIconButtonTouchTap={this.handleToggle.bind(this)}
                            showMenuIconButton={!!this.props.userData}
                        />
                    </header>
                    
                    <div style={styles.content} className={"qa-Application-content"}>
                        <div>{childrenWithContext}</div>
                    </div>
                </div>
            </MuiThemeProvider>
        )
    }
}





}


}


`

**Comment by gilbarbara** [comment] 2018-04-18 14:34
This will be possible with `skipBeacon` in the step options in V2 soon.
You can try it with `npm i react-joyride@next`

**Closed by gilbarbara** 2018-04-18 14:34 UTC
Labels: V2, feature

**Comment by gothraven** [comment] 2018-12-03 13:54
I would like to know if `skipBeacon` is available, thank you !

**Comment by YellowSmiley** [comment] 2019-01-30 15:34
I know this is closed but I've got V2 and it still isn't possible to use skipBeacon :(

**Comment by wolfmaster8** [comment] 2019-01-30 17:33
> I know this is closed but I've got V2 and it still isn't possible to use skipBeacon :(

Same here 😢

**Comment by wolfmaster8** [comment] 2019-01-30 17:59
@YellowSmiley try this in the steps:
```
{
    target: '.a',
    title: 'Hello',
    content: 'World',
    disableBeacon: true
  },
```

A problem I'm having, is that it's not scrolling automatically.

**Comment by hugobarragon** [comment] 2020-06-24 10:57
@gilbarbara any option to disable on the main component props?  
This would be great, because we only use one joyride component on our big platform, and uses redux to only pass the steps and run... on the previous version with autoStart this was possible, for now we had to place a disableBeacon prop on every step we have 😢

**Comment by gilbarbara** [comment] 2020-06-24 13:11
Hey @hugobarragon 

The autoStart in V1 was responsible for: `Open the tooltip automatically for the first step, without showing a beacon.`

So, for this behavior, you don't need to set `disableBeacon` for all steps, just the first one.
It doesn't matter where the steps came from and you can easily map the steps and change the props on the first one.

**Comment by hugobarragon** [comment] 2020-06-24 13:59
Hello @gilbarbara 

Thanks maybe I explained my self on a wrong way,
I know I can do that, for starting the joyride automatically, but I need to set the disable beacon on all steps to completely remove. If the user closes or clicks outside the next step will show the beacon for the user to click.Probably I will have to map all steps on this generic component on render time to add the disableBeacon by default.
i was searching for a prop with similiar behaviour to this ones:
https://docs.react-joyride.com/step#common-props-inheritance

something that allowed me to completly disable the beacon, but it could be overridable on the steps
example with same behaviour : 
`beaconComponent
disableCloseOnEsc
disableOverlay
disableOverlayClose
disableScrolling ...`

Maybe its only me or not, but does it make any sense for this solution to exist?
Anyway, we are setting on the this prop on every step, but probably will go with your suggestion for now, and create an algorithm to map and place it on every step, and on  a future if this lib implements it, it's easy to delete and just place the prop on the component, and save some lines on every other pages. 

ps: Initially, when I read the docs I thought it would work, because of the consistency on every prop you keep on the lib, normally, global goes on the component and it can be overwritten on the steps

**Comment by mac-s-g** [comment] 2021-01-14 21:30
First, thank you to the authors for providing an amazing module.

I don't think this issue should be closed.  Like others in the thread, my app is also using a menu based trigger.  the state is managed via the callback method.

mapping `disableBeacon: false` to each step effectively _hides_ the beacon but there is a problem with this approach:
The beacon is still rendered with `visibility:hidden`.  Because the beacon physically exists on the page, it can impact scrolling.

For example, if you set `disableBeacon` to true and use `body` as your trigger, you'll notice an issue with vertical scroll.  There's extra whitespace added underneath the document body containing a hidden beacon.

In my mind, the most intuitive change to Joyride's api would be to add a `disableBeacon` prop to the top level component.  When set to true, the beacon is not rendered at all.

**Comment by mac-s-g** [comment] 2021-01-15 00:29
fyi - my temporary workaround for the issue described above is the following:
```javascript
<Joyride
  ...
  beaconComponent={HiddenBeacon}
/>

//...

const HiddenBeacon = Styled.div`display: none;`
```

**Comment by gilbarbara** [comment] 2021-01-16 00:12
hey @mac-s-g

This issue is 4 years old. And it's the expected behavior and not a bug.

You can open a feature request in Discussions.
