### ISSUE TITLE
Possible to have Table of Contents as first step?

### ISSUE THREAD

**Issue by jduncanRadBlue** [gilbarbara/react-joyride#319] opened 2018-02-20 15:43 UTC
Hi!  We have been using joyride in our app and love it!  I do have a question to see if something is possible we are pondering.  We currently have the tour set up on a page with several steps.  The tour starts when the user clicks a link called "Page Tour" and goes through several different steps.  
Is it possible to have a first stop on the tour as a table of contents for what is to come in the tour?  This table of contents would also come with the ability to click links that would open up tour stops, rather than go through the entire tour?
Thanks!

**Comment by gilbarbara** [comment] 2018-02-20 17:05
I didn't understand what you mean...

You can change the `run` props if you need to stop the tour. Or show the TOC before starting the tour? ¯\_(ツ)_/¯

**Comment by jduncanRadBlue** [comment] 2018-02-20 17:32
Sorry for not explaining it well.  At the beginning of the tour we would like the first tooltip to show "welcome to the blah blah tour, here are the tour stops:
1. stop one
2. stop two
3. stop three"
but the user can click "stop three" and just go to that tooltip rather than go through the other steps first.
My question is how do we construct the code and where do we put the code for that table of contents?

**Comment by gilbarbara** [comment] 2018-02-20 17:42
This is an implementation problem that I can't help with, sorry.
You can try to share some code on codesandbox or something like it, but since is not a bug I will close it.

**Closed by gilbarbara** 2018-02-20 17:42 UTC

**Comment by gilbarbara** [comment] 2018-02-20 19:01
I'm a bit confused with steps/stops. Are they the same?
Do you want the user to click a link in the first STEP and go to STEP N or stop the tour and load some other component?

**Comment by jduncanRadBlue** [comment] 2018-02-20 19:34
Yes, sorry, step=stop in the tour.  So the first step will contain a table of contents, and a user could click one of the items listed to go to step n in the tour.
