### ISSUE TITLE
Misplaced spotlight position with custom scroll elements

### ISSUE THREAD

**Issue by Alpa84** [gilbarbara/react-joyride#594] opened 2020-08-10 22:25 UTC
## 🐛 Bug Report

The overlay position is misplaced when showing the second step of the scroll demo

## To Reproduce

visit https://codesandbox.io/s/github/gilbarbara/react-joyride-demo
go to 'scroll' tab
click the beacon
click Next
![Captura de Pantalla 2020-08-10 a la(s) 19 21 53](https://user-images.githubusercontent.com/4325762/89837313-16ca4a00-db3f-11ea-8c1b-12a806209418.png)

## Expected behavior

it should place the overlay on top of the 'Better error handling' header

## Link to repl or repo
https://codesandbox.io/s/github/gilbarbara/react-joyride-demo

**Comment by Alpa84** [comment] 2020-08-10 22:40
This does not happen when going from step 3 to step 2.
The problem seems to be related to using the html `scrollHeight` prop when getting the height of the `stylesOverlay`.
Only on step 2 (and coming from step 1)  `document.documentElement.scrollHeight` is greater than the `clientHeight` and `offsetHeight`.
Not including `document.documentElement.scrollHeight` to calculate the height of the overlay seems to fix the problem on the demo.

**Comment by gilbarbara** [comment] 2020-12-10 16:43
@Alpa84 I couldn't reproduce this right now.
Can you?

**Comment by AlexanderGuillermoSeguraBallesteros** [comment] 2021-03-16 02:27
Hello, I am having a similar issue, but sometimes the tour doesn't scroll, I have not been able to see the cause, I have cleaned all css but the behaviour is not fixed, I am using ant design, Is there any issue with this library? Because it does require to import antd css

**Comment by valtism** [comment] 2021-03-17 02:24
Here's a case where having `top: 60px` set on an absolute-positioned scrollable parent breaks the highlight position

https://codesandbox.io/s/shy-wind-6nz1p?file=/src/App.js

**Comment by valtism** [comment] 2021-03-17 02:51
Interestingly, it doesn't seem to have a problem when in fullscreen app mode (https://6nz1p.csb.app). I think the issue has to do with a performance slowdown interfering with the positioning of the highlight.

**Comment by valtism** [comment] 2021-03-17 07:52
The same thing happens with this similar example https://codesandbox.io/s/clever-lehmann-jkvop?file=/src/App.js except with an absolute-positioned content (similar to an issue I am facing)

I did some digging and it looks like the `getElementPosition` function is not returning the correct `top` value. I think that when there is a scroll parent, we should not be just returning `elementRect.top + (maybe)parent.scrollTop`, but should instead use `elementRect.top + parent.getBoundingClientRect().top`.

Even then, this may break in cases with nested scroll containers, but I didn't have time to test that case.

@gilbarbara

**Comment by delewis13** [comment] 2021-09-12 06:44
Just another codesandbox to add! Similar issues with incorrect spotlight position when attempting to spotlight a position within a scroll parent: https://codesandbox.io/s/react-joyride-scrolling-example-0k3e1?file=/src/App.js

**Comment by molhanec-work** [comment] 2022-01-21 10:47
@valtism Thanks, `@pry-financials/react-joyride` works for me...

**Comment by SanujBansal** [comment] 2022-09-16 15:35
@gilbarbara This PR fixed the position of spotlight where we don't have a scrolling parent #845
However, in case we have a scrolling parent due to incorrect scroll position, we still have the issue. Can you point to to the file where we are managing the scroll. Maybe I will be able to figure it out there as well.

**Comment by faangpath** [comment] 2022-09-26 16:56
> @gilbarbara This PR fixed the position of spotlight where we don't have a scrolling parent #845 However, in case we have a scrolling parent due to incorrect scroll position, we still have the issue. Can you point to to the file where we are managing the scroll. Maybe I will be able to figure it out there as well.

@gilbarbara Does this solution look good?

**Comment by gilbarbara** [comment] 2022-09-28 12:59
Hey @SanujBansal 
Thanks for the PR. However, we need a solution that works for both cases.
This issue is about custom scrolling elements.

**Comment by faangpath** [comment] 2022-09-29 08:23
@gilbarbara I believe @SanujBansal is happy to implement the other scenario. 

> Can you point to to the file where we are managing the scroll. Maybe I will be able to figure it out there as well.

If you could help out with a bit of context from your end, it is solvable.

**Comment by gilbarbara** [comment] 2022-09-29 17:19
It is the same function...

**Comment by JoeyAtSS** [comment] 2022-10-14 22:15
> Hello, I am having a similar issue, but sometimes the tour doesn't scroll, I have not been able to see the cause, I have cleaned all css but the behaviour is not fixed, I am using ant design, Is there any issue with this library? Because it does require to import antd css

I have the same issue, the tour doesnt scroll sometimes, which causes the spotlight to be out of place.

**Comment by gilbarbara** [comment] 2023-12-23 17:12
Fixed in 2.7.2
Thanks

**Closed by gilbarbara** 2023-12-23 17:12 UTC
Labels: bug, help wanted
